In [2]:
import pandas as pd
import numpy as np
import sqlite3

# Datasets:

# USER_TAKEHOME.csv file:

user_df = pd.read_csv('USER_TAKEHOME.csv')

# TRANSACTION_TAKEHOME.csv file:

transaction_df = pd.read_csv('TRANSACTION_TAKEHOME.csv')

# PRODUCTS_TAKEHOME.csv file:

products_df = pd.read_csv('PRODUCTS_TAKEHOME.csv')

# Missing values:

print("The number of Missing Values in the USER_TAKEHOME file:\n", user_df.isnull().sum())

# Total length of the file:

print("\nThe total length of the USER_TAKEHOME file:\n", len(user_df))

print("\nThe number of Missing Values in the TRANSACTION_TAKEHOME file:\n", transaction_df.isnull().sum())

# Total length of the file:

print("\nThe total length of the TRANSACTION_TAKEHOME file:\n", len(transaction_df))

print("\nThe number of Missing Values in the PRODUCTS_TAKEHOME file:\n", products_df.isnull().sum())

# Total length of the file:

print("\nThe total length of the PRODUCTS_TAKEHOME file:\n", len(products_df))




The number of Missing Values in the USER_TAKEHOME file:
 ID                  0
CREATED_DATE        0
BIRTH_DATE       3675
STATE            4812
LANGUAGE        30508
GENDER           5892
dtype: int64

The total length of the USER_TAKEHOME file:
 100000

The number of Missing Values in the TRANSACTION_TAKEHOME file:
 RECEIPT_ID           0
PURCHASE_DATE        0
SCAN_DATE            0
STORE_NAME           0
USER_ID              0
BARCODE           5762
FINAL_QUANTITY       0
FINAL_SALE           0
dtype: int64

The total length of the TRANSACTION_TAKEHOME file:
 50000

The number of Missing Values in the PRODUCTS_TAKEHOME file:
 CATEGORY_1         111
CATEGORY_2        1424
CATEGORY_3       60566
CATEGORY_4      778093
MANUFACTURER    226474
BRAND           226472
BARCODE           4025
dtype: int64

The total length of the PRODUCTS_TAKEHOME file:
 845552


# Observation:

% of missing values in each column of the files:

A. USER_TAKEHOME File:

1. BIRTH_DATE: 3675/100000 * 100 = 3.675%
2. STATE: 4812/100000 * 100 = 4.812%
3. LANGUAGE: 30508/100000 * 100 = 30.508%
4. GENDER: 5892/100000 * 100 = 5.892%

B. TRANSACTION_TAKEHOME File:

1. BARCODE: 5762/50000 * 100 = 11.524%

C. PRODUCTS_TAKEHOME File:

1. CATEGORY_1: 111/845552 * 100 = 0.013%
2. CATEGORY_2: 1424/845552 * 100 = 0.168%
3. CATEGORY_3: 60566/845552 * 100 = 7.71%
4. CATEGORY_4: 778093/845552 * 100 = 92.04%
5. MANUFACTURER: 226474/845552 * 100 = 26.78%
6. BRAND: 226472/845552 * 100 = 26.79%
7. BARCODE: 4025/845552 * 100 = 0.476%

In [3]:
# Unique values:

# Unique values in the State Column:

print("\n The unique values in the State column:", user_df['STATE'].unique())

# Unique values in the Gender Column:

print("\n The Unique Values in the GENDER column:", user_df['GENDER'].unique())

# Unique values in the Language Column:

print("\n The Unique Values in the LANGUAGE column:", user_df['LANGUAGE'].unique())



 The unique values in the State column: ['CA' 'PA' 'FL' 'NC' 'NY' 'IN' nan 'OH' 'TX' 'NM' 'PR' 'CO' 'AZ' 'RI' 'MO'
 'NJ' 'MA' 'TN' 'LA' 'NH' 'WI' 'IA' 'GA' 'VA' 'DC' 'KY' 'SC' 'MN' 'WV'
 'DE' 'MI' 'IL' 'MS' 'WA' 'KS' 'CT' 'OR' 'UT' 'MD' 'OK' 'NE' 'NV' 'AL'
 'AK' 'AR' 'HI' 'ME' 'ND' 'ID' 'WY' 'MT' 'SD' 'VT']

 The Unique Values in the GENDER column: ['female' nan 'male' 'non_binary' 'transgender' 'prefer_not_to_say'
 'not_listed' 'Non-Binary' 'unknown' 'not_specified'
 "My gender isn't listed" 'Prefer not to say']

 The Unique Values in the LANGUAGE column: ['es-419' 'en' nan]


In [4]:
# Non-numeric values in FINAL_QUANTITY and FINAL_SALE:

non_numeric_quantity = transaction_df[~transaction_df['FINAL_QUANTITY'].str.replace('.', '', 1).str.isnumeric()]

print("\n The Non-Numeric Values in the FINAL_QUANTITY column:\n", non_numeric_quantity[['FINAL_QUANTITY']].head())

# Finding values other than numeric in Final sale column:

non_numeric_sale = transaction_df[~transaction_df['FINAL_SALE'].str.replace('.', '', 1).str.isnumeric()]

print("\n The Non-Numeric Values in the FINAL_SALE column:\n", non_numeric_sale[['FINAL_SALE']].head())



 The Non-Numeric Values in the FINAL_QUANTITY column:
   FINAL_QUANTITY
1           zero
3           zero
5           zero
7           zero
9           zero

 The Non-Numeric Values in the FINAL_SALE column:
   FINAL_SALE
0           
2           
4           
6           
8           


# Observation:

It can be seen that the FINAL_QUANTITY column has the value zero in it along with others. Similarly, FINAL_SALE column has blank values.

In [5]:
# Ambiguous fields in PRODUCTS_TAKEHOME:

am1 = products_df['CATEGORY_1'].unique()

am2 = products_df['CATEGORY_2'].unique()

am3 = products_df['CATEGORY_3'].unique()

print("\nThe Unique Values in CATEGORY_4:", am1[:10])

print("\nUnique Values in MANUFACTURER:", am2[:10])

print("\nUnique Values in BRAND:", am3[:10])


The Unique Values in CATEGORY_4: ['Health & Wellness' 'Snacks' 'Beverages' 'Pantry' 'Alcohol'
 'Apparel & Accessories' 'Restaurant' 'Needs Review' 'Dairy'
 'Home & Garden']

Unique Values in MANUFACTURER: ['Sexual Health' 'Puffed Snacks' 'Hair Care' 'Oral Care'
 'Medicines & Treatments' 'Deodorant & Antiperspirant' 'Snack Bars' nan
 'Bath & Body' 'Nuts & Seeds']

Unique Values in BRAND: ['Conductivity Gels & Lotions' 'Cheese Curls & Puffs'
 'Hair Care Accessories' 'Toothpaste' 'Essential Oils'
 'Vitamins & Herbal Supplements' "Men's Deodorant & Antiperspirant"
 'Granola Bars' nan 'Skin Treatments']


# Conclusion:

A. Missing Data Issues:

USER_TAKEHOME:

1. The BIRTH_DATE column contains 3,675 missing values primarily because of incomplete user profiles. STATE column has 4,812 missing values due to data collection gaps.

2. LANGUAGE column has the most missing values, 30,508 missing values. This issue can impact personalized services for customers of various languages.

3. GENDER contains 5,892 missing values. This suggests that there is data inconsistency in demographic attributes.

TRANSACTION_TAKEHOME:

1. The BARCODE column in this file has 5,762 missing values. This indicates that some of the transactions may not have details in the product-level.

PRODUCTS_TAKEHOME:

1. CATEGORY_1: There are 111 missing values in CATEGORY_1 column. It is not so big of an issue but there should be steps taken to remove these missing values.

2. CATEGORY_2 has 1,424 missing values. This may be possible as there is incomplete categorization.

3. There are 60,566 missing values in CATEGORY_3. This column has plenty of missing subcategories.

4. There are 92.04% missing values in CATEGORY_4. This field is mostly not used.

5. MANUFACTURER column has 226,474 missing values. Product metadata has potential problems here.

6. BRAND has 226,472 missing values. The majority of products have unclear affiliations of brands.

7. BARCODE has 4,025 missing values. This possibly can affect tracking of products and their analysis.

➡ Observation:

The large number of missing values in CATEGORY_3, CATEGORY_4, MANUFACTURER, and BRAND columns suggest that the product dataset might not have been properly maintained.
For accurate sales, it is necessary to fill in the missing values for the BARCODE column.

B. Inconsistent or Ambiguous Data

1. GENDER values in USER_TAKEHOME:

There is inconsistent formatting of the data in the GENDER column of USER_TAKEHOME file. Also, there are multiple variations of the word "unknown" like for instance "unknown", "not_specified", "Prefer not to say", and "My gender isn't listed". The options should be standardized

2. LANGUAGE values in USER_TAKEHOME:

The LANGUAGE column in the USER_TAKEHOME table consists of 2 values - "en" and "es-419". Furthermore, there are nearly 30% missing values. Latin American Spanish is defined by regional code es-419, it may not be that easily comprehensible for most of the people.


➡ Observation:

It can easily be observed that:

Gender classifications need standardization. There is limited language data, which hinders its applicability to segmentation.

#SQL Queries:

# Question 1:

What are the top 5 brands by receipts scanned among users 21 and over?

In [ ]:
query = """
SELECT COALESCE(p.BRAND, 'Unknown Brand') AS BRAND, COUNT(t.RECEIPT_ID) AS total_rec
FROM TRANSACTION_TAKEHOME t JOIN USER_TAKEHOME u
ON t.USER_ID = u.ID
JOIN PRODUCTS_TAKEHOME p ON p.BARCODE = t.BARCODE
WHERE CAST(strftime('%Y', 'now') AS INT) - CAST(strftime('%Y', u.BIRTH_DATE) AS INT) >= 21 -- Age should be greater than 21 here
GROUP BY p.BRAND
ORDER BY total_rec DESC
LIMIT 5;
"""

# In-memory SQLite connection:

conn = sqlite3.connect(':memory:')

# Loading these dataframes as tables:

user_df.to_sql('USER_TAKEHOME', conn, if_exists='replace', index=False)
transaction_df.to_sql('TRANSACTION_TAKEHOME', conn, if_exists='replace', index=False)
products_df.to_sql('PRODUCTS_TAKEHOME', conn, if_exists='replace', index=False)

# Query Execution:

top_5_brands = pd.read_sql_query(query, conn)
print(top_5_brands)

# Closing the connection after execution:

conn.close()


             BRAND  total_rec
0      NERDS CANDY          6
1             DOVE          6
2    Unknown Brand          6
3          TRIDENT          4
4  SOUR PATCH KIDS          4


#Observation:

The top 5 brands by receipts scanned among users 21 and over are:

1. Nerds Candy
2. Dove
3. Unknown Brand
4. Trident
5. Sour Patch Kids

# Question 2:

Which is the leading brand in the Dips & Salsa category?

In [ ]:

# Define the SQL query

query = """
SELECT COALESCE(p.BRAND, 'Unknown Brand') AS BRAND,
    COUNT(t.RECEIPT_ID) AS total_sales
FROM TRANSACTION_TAKEHOME t
JOIN PRODUCTS_TAKEHOME p ON t.BARCODE = p.BARCODE
WHERE
    LOWER(p.CATEGORY_3) LIKE '%dip%'
    OR LOWER(p.CATEGORY_3) LIKE '%salsa%'
GROUP BY p.BRAND
ORDER BY total_sales DESC
LIMIT 1;
"""

# In-memory SQLite connection:

conn = sqlite3.connect(':memory:')

# Loading these dataframes as tables:

user_df.to_sql('USER_TAKEHOME', conn, if_exists='replace', index=False)
transaction_df.to_sql('TRANSACTION_TAKEHOME', conn, if_exists='replace', index=False)
products_df.to_sql('PRODUCTS_TAKEHOME', conn, if_exists='replace', index=False)

# Query Execution:

top_dips_salsa = pd.read_sql_query(query, conn)
print(top_dips_salsa)

# Closing the connection after execution:

conn.close()


      BRAND  total_sales
0  TOSTITOS           72


# Observation:

The leading brand in the Dips & Salsa category is Tostitos.

# Question 3:

What are the top 5 brands by sales among users that have had their account for at least six months?

In [ ]:
query = """
SELECT COALESCE(p.BRAND, 'Unknown Brand') AS BRAND, SUM(t.FINAL_SALE) AS sales_total
FROM TRANSACTION_TAKEHOME t
JOIN USER_TAKEHOME u ON t.USER_ID = u.ID
JOIN PRODUCTS_TAKEHOME p ON t.BARCODE = p.BARCODE
WHERE u.CREATED_DATE <= date('now', '-6 months')
GROUP BY BRAND
ORDER BY sales_total DESC
LIMIT 5;
"""

# In-memory SQLite connection:

conn = sqlite3.connect(':memory:')

# Loading these dataframes as tables:

user_df.to_sql('USER_TAKEHOME', conn, if_exists='replace', index=False)
transaction_df.to_sql('TRANSACTION_TAKEHOME', conn, if_exists='replace', index=False)
products_df.to_sql('PRODUCTS_TAKEHOME', conn, if_exists='replace', index=False)

# Query Execution:

top_5_sales = pd.read_sql_query(query, conn)
print(top_5_sales)

# Closing the connection after execution:

conn.close()

           BRAND  sales_total
0            CVS        72.00
1        TRIDENT        46.72
2           DOVE        42.88
3    COORS LIGHT        34.96
4  Unknown Brand        16.65


#Observation:

The top 5 brands by sales among users that have had their account for at least six months:

1. CVS
2. Trident
3. Dove
4. Coors Light
5. None

# Slack Message:

Hello Stakeholder,

I hope you're doing well. I've been working with our data and thought I'd outline some of the most important observations, along with some questions that would need further clarification.

Significant Data Quality Issues are as follows:

A. Missing Values:

- BIRTH_DATE has 3.675% missing values, STATE has around 4.8% missing values, LANGUAGE column (30.508% missing), and GENDER column has 5.892% missing values in user data.

- BARCODE has 11.524% missing values for transactions dataset. It may affect our power to compare products.

- MANUFACTURER and BRAND columns have approximately 27% missing values in the products dataset. It hinders the analysis at brand level.

- CATEGORY_4 has highest % missing values and proper measures should be taken on it on a high priority.

Data Consistency Concerns:

- FINAL_QUANTITY column in the transaction dataset contains the text "zero" instead of 0.0, which needs to be cleaned. FINAL_SALE column contains blank rows so it is not known if those sales were of zero cost or were mistakenly recorded.

Interesting Trend Identified:

- Top Brand in Dips & Salsa Category: Tostitos with 72 transactions being made, which points towards a dominant market share. Maybe it would be helpful to study what drives its success (price, promotions, or brand loyalty).

Outstanding Questions & Next Steps:

- Can we please get some clarification on how missing BARCODE values are generated? Are they caused by scanning errors or missing product data?
- Should "zero" in FINAL_QUANTITY be interpreted as 0 or Nan ? Does this indicate an issue in the data gathering process?
- Would you rather have more granularity on user purchase behavior by state, language, or gender (even with the missing values)?
- Would love to discuss these points with you and align on the next steps. Kindly let me know if you’d like to schedule a quick sync.

Thank you,
Renuka